on:
  push:
    branches:
      - master
name: ğŸš€ Deploy via ftp
jobs:
  deploy:
    name: ğŸ‰ Deploy!!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ“ Criar pasta temporÃ¡ria
        run: mkdir temp_deploy
      - name: ğŸ—‚ï¸ Mover arquivos para a pasta temporÃ¡ria
        run: mv dist/* temp_deploy/
      - name: ğŸ“ Renomear pasta temporÃ¡ria para public_html
        run: mv temp_deploy public_html
      - name: ğŸ—‘ï¸ Remover pasta dist antiga
        run: rm -rf dist
      - name: ğŸŒ Agora sim! Deploy para Locaweb ğŸš€
        uses: locaweb/ftp-deploy@v1
        with:
          host: ${{ secrets.LOCAWEB_HOST }}
          user: ${{ secrets.LOCAWEB_USER }}
          password: ${{ secrets.LOCAWEB_PASSWORD }}
          localDir: public_html